title: Spring POST Lesson
description: "August 2023 to June 2024"
owner_name: Spring POSTS
baseurl: "/springpostlesson"
remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
future: true
